## Neural Networks

Nb of rows is equal to nb on neurons, the multiplicatoin is done W . X 

In [1]:
import numpy as np
np.set_printoptions(precision=3)

### Activation  Functions

In [2]:
def sigmoid(v):
    return (1 / (1+ np.exp(-v)) )

In [3]:
sigmoid(0.04)

0.5099986668799655

In [4]:
def relu(v):
    if v<0:
        return 0
    else:
        return 1    

In [5]:
def threshold(v):
    if v < 0:
        return 0
    else:
        return 1

In [6]:
def tanh(v):
    return( 1-np.exp(-v) / ( 1 + np.exp(-v) ) )

In [7]:
def MSE(y, yhat):
    m =len(y)
    err = 0.0
    for i in range(m):
        err += np.square(y[i]-yhat[i])
    err = (1/2*m)*err
    return(err)

In [8]:
def add_bias(X_):
    return np.append(X_,1)

In [9]:
def forward_prop(W_,X_,fn=sigmoid):
    if W_.shape[1] != X_.shape[0]:
        print("The matrix columns and the input length are not similar.")
        return
    output = fn(np.matmul(W_,X_)) #the sigmoid of the scalar product of X and column i of W
    return output

In [10]:
def delta_output_layer_fn(W_output_, desired_,  Y_in_, a=1):
    output_ = forward_prop(W_output_,Y_in_)
    delta_output_layer = a * (desired - output_) * output_ * (1- output_)    
    return delta_output_layer

In [11]:
#Take X as input matrix not one by on

In [12]:
def delta_hidden_layer_fn(W_local, W_next,X_input,delta_next):
    Y_j = forward_prop(W_local,X_input)
    r_local , c_local = W_local.shape
    r_next, c_next = W_next.shape
    delta_hidden = np.zeros(r_local)
    for j in range(r_local):
        delta_j_next_sum = 0
        for k in range(r_next):
            delta_j_next_sum += delta_next[k] * W_next[k,j]
        delta_hidden[j] = a * Y_j[j] * (1-Y_j[j]) * delta_j_next_sum
    return delta_hidden

### Try in random simple input

In [13]:
input_length = 3
L1_neuron_nb = 6
L2_neuron_nb = 2
np.random.seed(10)

In [14]:
X1 = np.random.rand(input_length)
X1= add_bias(X1)

In [15]:
#Forwarad prop to get Y1, output
W1 = np.random.rand(L1_neuron_nb , input_length +1)
Y1 = add_bias(forward_prop(W1,X1))

W2 = np.random.rand(L2_neuron_nb , L1_neuron_nb +1 )
output = forward_prop(W2,Y1)
print(output)

[0.971 0.898]


In [16]:
print(X1)

[0.771 0.021 0.634 1.   ]


In [17]:
print(W1)

[[0.749 0.499 0.225 0.198]
 [0.761 0.169 0.088 0.685]
 [0.953 0.004 0.512 0.813]
 [0.613 0.722 0.292 0.918]
 [0.715 0.543 0.142 0.373]
 [0.674 0.442 0.434 0.618]]


In [18]:
print(Y1)

[0.717 0.791 0.867 0.831 0.736 0.806 1.   ]


In [19]:
print(W2)

[[0.513 0.65  0.601 0.805 0.522 0.909 0.319]
 [0.09  0.301 0.114 0.829 0.047 0.626 0.548]]


In [20]:
print(output)

[0.971 0.898]


### Back Propagation with activation = sigmoid

In [21]:
#Back Propagation
desired = np.array([0,0])

In [22]:
print(desired)

[0 0]


In [100]:
print(output)

[0.9709  0.89812]


In [101]:
print(MSE(output,desired))

1.7492621503670986


In [23]:
a = 1
eta = 0.3

In [24]:
epochs = 100

for e in range(epochs):
    Y1 =  add_bias(forward_prop(W1,X1))
    output_ = forward_prop(W2,Y1)
    r1,c1 = W1.shape
    r2,c2 = W2.shape
    delta_j_output = delta_output_layer_fn(W2,desired, Y1)
    for i in range(c2):
        for j in range(r2):
            W2[j,i] = W2[j,i] +( eta *  delta_j_output[j] * Y1[i])

    delta_j_1 = delta_hidden_layer_fn(W1,W2,X1,delta_j_output)
    for i in range(c1):
        for j in range(r1):
            W1[j,i] = W1[j,i] +(eta * delta_j_1[j] * X1[i])
    e+=1

In [25]:
Y1_test = forward_prop(W1,X1)
Y1_test=add_bias(Y1_test)
output_test = forward_prop(W2,Y1_test)
print("output test" , output_test)
print("desired values", desired)

output test [0.084 0.072]
desired values [0 0]


In [26]:
print(MSE(output,desired))
print(MSE(output_test, desired))

1.7492621503670986
0.012125720008188609
