## Neural Networks

In [1]:
import numpy as np
np.set_printoptions(precision=4)

### Activation  Functions

In [2]:
def sigmoid(v):
    return (1 / (1+ np.exp(-v)) )
def threshold(v):
    if v < 0:
        return 0
    else:
        return 1
def tanh(v):
    return( 1-np.exp(-v) / ( 1 + np.exp(-v) ) )


### Try in random simple input

In [3]:
#Example values
input_nb = 3
L1_n = 4 # nb of neurons in Layer 1
L2_n = 4 # nb of neurons in Layer 2

In [4]:
X1 = np.random.rand(input_nb)    # input is a numpy array of shape (n,), we should add +1 to the array for the bias

#matrix W1 is of shape rows = nb of cols of previous array, cols = nb of neurons we want to make
W1 = np.random.rand(input_nb +1 ,L1_n)  
W2 = np.random.rand(L1_n+1, L2_n) 

In [5]:
print("X1 without bias:",X1)
print("shape of X1" , X1.shape,"\n")

print("W1:\n", W1)
print("shape of W1:", W1.shape, "\n")
print("W2:,\n", W2)
print("shape of W2: ", W2.shape, "\n")


X1 without bias: [0.5645 0.7655 0.2019]
shape of X1 (3,) 

W1:
 [[0.1882 0.2387 0.1158 0.902 ]
 [0.8861 0.9866 0.7955 0.1544]
 [0.9064 0.8246 0.3111 0.158 ]
 [0.3424 0.3009 0.3289 0.3468]]
shape of W1: (4, 4) 

W2:,
 [[0.7952 0.7318 0.0452 0.2742]
 [0.8526 0.3544 0.741  0.9427]
 [0.4656 0.6707 0.9042 0.0146]
 [0.1055 0.4706 0.9328 0.4938]
 [0.0777 0.763  0.7502 0.7391]]
shape of W2:  (5, 4) 



In [6]:
X1 = np.append(X1,1) #add +1 to end of X for the bias
print("X1 with bias: ", X1,"\n")

X1 with bias:  [0.5645 0.7655 0.2019 1.    ] 



In [8]:
#Forward propagation takes an input X, a matrix representing the coeficiants of neurons, and an activation function
def forward_prop(X,W,fn=sigmoid):
    X_length = X.shape[0] #length of X 
    W_rows,W_cols = W.shape #nb of rows and columns on matrix W    
    if W_rows != X_length:
        print("Not proprtional size")
        return
    output = np.zeros(W_cols)
    for i in range(W_cols): 
        output[i] = fn( (np.dot(X, W[:,i]) )) #the sigmoid of the scalar product of X and column i of W
           
    return output

In [9]:
#TRY forward_prop
print("w1: ", W1)
Y1 = forward_prop(X1,W1,sigmoid)
print("Y1 wihtout Bias: ", Y1)

Y1 = np.append(Y1,1)
print("Y1 with bias: ", Y1)
Y2 = forward_prop(Y1, W2, threshold)
print("Y2:" , Y2)

w1:  [[0.1882 0.2387 0.1158 0.902 ]
 [0.8861 0.9866 0.7955 0.1544]
 [0.9064 0.8246 0.3111 0.158 ]
 [0.3424 0.3009 0.3289 0.3468]]
Y1 wihtout Bias:  [0.7875 0.7953 0.7438 0.7323]
Y1 with bias:  [0.7875 0.7953 0.7438 0.7323 1.    ]
Y2: [1. 1. 1. 1.]


In [15]:
print("X1 with bias:\n", X1)
print("w1:\n", W1,"\n")
print("Y1:\n", Y1,"\n")
print("Y1 with bias:\n", Y1,"\n")
print("Y2:\n" , Y2)

X1 with bias:
 [0.7626 0.1639 0.198  1.    ]
w1:
 [[0.4596 0.9449 0.385  0.0526]
 [0.7746 0.7359 0.0659 0.8647]
 [0.5288 0.4026 0.7178 0.0466]
 [0.8678 0.05   0.7516 0.3112]] 

Y1:
 [0.81   0.7253 0.7682 0.623  1.    ] 

Y1 with bias:
 [0.81   0.7253 0.7682 0.623  1.    ] 

Y2:
 [1. 1. 1. 1.]


In [10]:
#Back Propagation
def back_prop(X,W,d,eta=1,fn=sigmoid):
    X_length = X.shape[0] #length of X 
    y = forward_prop(X,W,fn)
    W_rows,W_cols = W.shape #nb of rows and columns on matrix W 
    n = d.shape[0] 
    e_n = np.zeros_like(y)
    for i in range(n):
        e_n[i]=d[i]-y[i] #error vector for all outputs (their nb is equal to nb of neurons of previous layer)
        
    for i in range(W_cols): #rectify values of each value of each column of W
        W_i =  W[:,i]
        for j in range(W_i.shape[0]):
            W_i[j] = W_i[j] + (eta * (e_n[i]*X[j])  )
        W[:,i] = W_i

    return W

In [12]:
desired_Y=np.array([1,0,1,1])
print(desired_Y)

[1 0 1 1]


In [13]:
#W1 before and after one backpropagation
print("w1:\n" ,W1, "\n")
W1_after_back_prop = back_prop(X1,W1,desired_Y,1)
print("W1 after backprop one time:\n" , W1_after_back_prop)

w1:
 [[0.1882 0.2387 0.1158 0.902 ]
 [0.8861 0.9866 0.7955 0.1544]
 [0.9064 0.8246 0.3111 0.158 ]
 [0.3424 0.3009 0.3289 0.3468]] 

W1 after backprop one time:
 [[ 0.3081 -0.2103  0.2604  1.0531]
 [ 1.0488  0.3778  0.9916  0.3594]
 [ 0.9494  0.664   0.3628  0.2121]
 [ 0.5549 -0.4944  0.585   0.6146]]


In [23]:
#Question: If we have many layers, what is desired y in layers beofre the last one??

In [14]:
def MSE(y, yhat):
    m =len(y)
    err = 0.0
    for i in range(m):
        err += np.square(y[i]-yhat[i])
    err = (1/2*m)*err
    return(err)

In [15]:
epochs = 5; ctr =0
W_temp = W1

while ctr<epochs:
    W_temp = back_prop(X1,W_temp,desired_Y,1)
    ctr += 1

In [16]:
predicted_Y = forward_prop(X1,W_temp,threshold)
print("Desired Y: ", desired_Y)
print("Predicted value:" , predicted_Y,"\n")

Desired Y:  [1 0 1 1]
Predicted value: [1. 0. 1. 1.] 



In [17]:
MSE(desired_Y, predicted_Y)

0.0