## Neural Networks

Nb of rows is equal to nb on neurons, the multiplicatoin is done W . X 

In [1]:
import numpy as np
np.set_printoptions(precision=4)

### Activation  Functions

In [2]:
def sigmoid(v):
    return (1 / (1+ np.exp(-v)) )

In [3]:
def threshold(v):
    if v < 0:
        return 0
    else:
        return 1

In [4]:
def tanh(v):
    return( 1-np.exp(-v) / ( 1 + np.exp(-v) ) )

In [31]:
def MSE(y, yhat):
    m =len(y)
    err = 0.0
    for i in range(m):
        err += np.square(y[i]-yhat[i])
    err = (1/2*m)*err
    return(err)

In [46]:
def add_bias(X_):
    return np.append(X_,1)

### Try in random simple input

In [55]:
W1 = np.random.rand(3 ,7)  
X1 = np.random.rand(6)

In [56]:
W1

array([[0.8658, 0.6653, 0.5742, 0.008 , 0.3121, 0.4809, 0.7244],
       [0.8276, 0.1654, 0.2351, 0.8654, 0.0431, 0.5122, 0.8467],
       [0.1811, 0.7474, 0.6298, 0.3448, 0.8491, 0.3902, 0.1461]])

In [57]:
X1

array([0.3031, 0.1095, 0.8778, 0.191 , 0.3793, 0.0768])

In [65]:
def forward_prop1(W_,X_,fn=sigmoid): #add bias
    X_length = X_.shape[0] #length of X 
    W_rows,W_cols = W_.shape #nb of rows and columns on matrix W    
    if W_cols != X_length:
        print("The matrix columns and the input length are not similar.")
        return
    output = np.zeros(W_rows) # nb of rows is equal to nb of neurons
    for i in range(W_rows): 
        output[i] = fn( (np.dot(W_[i,:] ,X_) )) #the sigmoid of the scalar product of X and column i of W
    return output

In [66]:
def forward_prop2(W_,X_,fn=sigmoid): #add bias
    X_length = X_.shape[0] #length of X 
    W_rows,W_cols = W_.shape #nb of rows and columns on matrix W    
    if W_cols != X_length:
        print("The matrix columns and the input length are not similar.")
        return
    output = np.matmul(W_,X_) #the sigmoid of the scalar product of X and column i of W
    return output

In [58]:
X1 = add_bias(X1)

In [61]:
Y1 = forward_prop(W1,X1)

X2 = np.random.rand(4,3)
r = forward_prop(X2,Y1)
print(r)

[0.7413 2.9576 1.0677 1.5654]


In [62]:
X1

array([0.3031, 0.1095, 0.8778, 0.191 , 0.3793, 0.0768, 1.    ])

In [64]:
Y1 = forward_prop(W1,X1)

X2 = np.random.rand(4,3)
r = forward_prop(X2,Y1)
print(r)

[0.8146 0.6575 0.8666 0.8677]


In [68]:
print(forward_prop1(W1,X1))
print(forward_prop2(W1,X1))

[0.8482 0.8239 0.7779]
[1.7205 1.543  1.2536]
