## Neural Networks

Nb of rows is equal to nb on neurons, the multiplicatoin is done W . X 

In [207]:
import numpy as np
np.set_printoptions(precision=3)

### Activation  Functions

In [208]:
def sigmoid(v):
    return (1 / (1+ np.exp(-v)) )

In [209]:
def relu(v):
    if v<0:
        return 0
    else:
        return 1    

In [210]:
def threshold(v):
    if v < 0:
        return 0
    else:
        return 1

In [211]:
def tanh(v):
    return( 1-np.exp(-v) / ( 1 + np.exp(-v) ) )

In [212]:
def MSE(y, yhat):
    m =len(y)
    err = 0.0
    for i in range(m):
        err += np.square(y[i]-yhat[i])
    err = (1/2*m)*err
    return(err)

In [213]:
def add_bias(X_):
    return np.append(X_,1)

In [214]:
def forward_prop(W_,X_,fn=sigmoid):
    if W_.shape[1] != X_.shape[0]:
        print("The matrix columns and the input length are not similar.")
        return
    output = fn(np.matmul(W_,X_)) #the sigmoid of the scalar product of X and column i of W
    return output

In [215]:
#def back_prop():
    
    

In [443]:
def delta_output_layer_fn(W_output_, desired_,  Y_in_, a=1):
    output_ = forward_prop(W_output_,Y_in_)
    delta_output_layer = a * (desired - output_) * output_ * (1- output_)    
    return delta_output_layer

In [444]:
def delta_hidden_layer():
    return

### Try in random simple input

In [445]:
input_length = 3
L1_neuron_nb = 6
L2_neuron_nb = 2
np.random.seed(10)

In [446]:
X1 = np.random.rand(input_length)
X1= add_bias(X1)

In [447]:
#Forwarad prop to get Y1, output
W1 = np.random.rand(L1_neuron_nb , input_length +1)
Y1 = add_bias(forward_prop(W1,X1))

W2 = np.random.rand(L2_neuron_nb , L1_neuron_nb +1 )
output = forward_prop(W2,Y1)
print(output)

[0.971 0.898]


In [448]:
print(X1)

[0.771 0.021 0.634 1.   ]


In [449]:
print(W1)

[[0.749 0.499 0.225 0.198]
 [0.761 0.169 0.088 0.685]
 [0.953 0.004 0.512 0.813]
 [0.613 0.722 0.292 0.918]
 [0.715 0.543 0.142 0.373]
 [0.674 0.442 0.434 0.618]]


In [450]:
print(Y1)

[0.717 0.791 0.867 0.831 0.736 0.806 1.   ]


In [451]:
print(W2)

[[0.513 0.65  0.601 0.805 0.522 0.909 0.319]
 [0.09  0.301 0.114 0.829 0.047 0.626 0.548]]


In [452]:
print(output)

[0.971 0.898]


### Back Propagation with activation = sigmoid

In [453]:
#Back Propagation
desired = np.array([1,0])

In [454]:
print(desired)

[1 0]


In [455]:
print(output)

[0.971 0.898]


In [456]:
a = 1
eta = 5

In [431]:
delta_j_output_layer = a * (desired - output) * output * (1 - output)
delta_j_output_layer

array([ 0.   , -0.107])

In [399]:
r1,c1 = W1.shape
r2,c2 = W2.shape

In [400]:
#back_prop for W2 (output layer)
for j in range(r2):
    for i in range(c2):
        W2[j,i] = W2[j,i] + (eta * ( delta_j_output_layer[j]) * Y1[i])

In [401]:
W2 

array([[ 0.516,  0.654,  0.605,  0.809,  0.525,  0.912,  0.323],
       [-0.204, -0.024, -0.242,  0.487, -0.256,  0.295,  0.137]])

In [402]:
#Calculate delta_J(n) for hidden layer
delta_j_hidden_layer = np.zeros(L1_neuron_nb)
for j in range(L1_neuron_nb):
    delta_j_next_sum = 0 
    for k in range(L2_neuron_nb):
        delta_j_next_sum += delta_j_output_layer[k] * W2[k,j]
    delta_j_hidden_layer[j] = a * Y1[j] * (1-Y1[j]) * delta_j_next

In [411]:
def delta_hidden_layer_fn(W_local, W_next,X_input,delta_next):
    Y_j = forward_prop(W_local,X_input)
    r_local , c_local = W_local.shape
    r_next, c_next = W_next.shape
    delta_hidden = np.zeros(r_local)
    for j in range(r_local):
        delta_j_next_sum = 0
        for k in range(r_next):
            delta_j_next_sum += delta_next[k] * W_next[k,j]
        delta_hidden[j] = a * Y_j[j] * (1-Y_j[j]) * delta_j_next_sum
    return delta_hidden
    

In [404]:
#back prop for W1 (hidden layer)
for i in range(c1):
    for j in range(r1):
        W1[j,i] = W1[j,i] + eta * delta_j_hidden_layer[j] * X1[i]

In [405]:
print(W1,"\n")
print(W2)

[[0.749 0.499 0.225 0.198]
 [0.761 0.169 0.088 0.686]
 [0.953 0.004 0.512 0.813]
 [0.613 0.722 0.292 0.918]
 [0.715 0.543 0.142 0.374]
 [0.674 0.442 0.434 0.618]] 

[[ 0.516  0.654  0.605  0.809  0.525  0.912  0.323]
 [-0.204 -0.024 -0.242  0.487 -0.256  0.295  0.137]]


In [432]:
epochs = 100

for e in range(epochs):
    Y1 =  add_bias(forward_prop(W1,X1))
    output = forward_prop(W2,Y1)
    
    delta_j_output_layer = a * (desired - output) * output * (1 - output)
    
    for i in range(c2):
        for j in range(r2):
            W2[j,i] = W2[j,i] +( eta *  delta_j_output_layer[j] * Y1[i])
            
    delta_j_hidden  = np.zeros(L1_neuron_nb)
    for j in range(L1_neuron_nb):
        delta_j_next = 0 
        for k in range(L2_neuron_nb):
            delta_j_next += delta_j_output_layer[k] * W2[k,j]
        delta_j_hidden[j] = a * Y1[j] * (1-Y1[j]) * delta_j_next
        
    for i in range(c1):
        for j in range(r1):
            W1[j,i] = W1[j,i] +(eta * delta_j_hidden[j] * X1[i])
    e+=1

In [442]:
delta_j_output = delta_output_layer_fn(W2,desired,Y1)
delta_j_output

array([ 0.009, -0.054])

In [457]:
epochs = 100

for e in range(epochs):
    Y1 =  add_bias(forward_prop(W1,X1))
    output = forward_prop(W2,Y1)
    
    delta_j_output = delta_output_layer_fn(W2,desired,Y1)
    for i in range(c2):
        for j in range(r2):
            W2[j,i] = W2[j,i] +( eta *  delta_j_output[j] * Y1[i])

    delta_j_1 = delta_hidden_layer_fn(W1,W2,X1,delta_j_output)
    for i in range(c1):
        for j in range(r1):
            W1[j,i] = W1[j,i] +(eta * delta_j_1[j] * X1[i])
    e+=1

In [458]:
Y1_test = forward_prop(W1,X1)
Y1_test=add_bias(Y1_test)
output_test = forward_prop(W2,Y1_test)
print("output test" , output_test)
print("desired values", desired)

output test [0.988 0.013]
desired values [1 0]


In [408]:
print(W1)
print(W2)

[[0.86  0.501 0.316 0.342]
 [0.839 0.171 0.153 0.787]
 [1.029 0.006 0.574 0.91 ]
 [0.636 0.722 0.312 0.949]
 [0.829 0.546 0.236 0.522]
 [0.721 0.443 0.472 0.678]]
[[ 0.629  0.775  0.736  0.932  0.64   1.033  0.471]
 [-0.866 -0.75  -1.034 -0.269 -0.935 -0.44  -0.773]]


In [409]:
Y1_test

array([0.771, 0.823, 0.888, 0.839, 0.79 , 0.824, 1.   ])