In [1]:
import numpy as np
from numpy.linalg import matrix_power
from numpy import linalg as LA

In [2]:
P2 = np.array(
[ [0,0,1,0,0,0],
[0,0,1,0,0,0],
[0.25,0.25,0,0.25,0.25,0],
[0,0,0.5,0,0,0.5],
[0,0,0.5,0,0,0.5],
[0,0,0,0.5,0.5,0]])

In [3]:
Pi = [1/12, 1/12, 4/12, 2/12, 2/12, 2/12 ]
Pi

[0.08333333333333333,
 0.08333333333333333,
 0.3333333333333333,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666]

In [27]:
print(Pi @ matrix_power(P2,103))

[0.08333333 0.08333333 0.33333333 0.16666667 0.16666667 0.16666667]


In [19]:
for i in range(200,204):
    print(matrix_power(P2,i))
    print("===============")

[[0.16666667 0.16666667 0.         0.33333333 0.33333333 0.        ]
 [0.16666667 0.16666667 0.         0.33333333 0.33333333 0.        ]
 [0.         0.         0.66666667 0.         0.         0.33333333]
 [0.16666667 0.16666667 0.         0.33333333 0.33333333 0.        ]
 [0.16666667 0.16666667 0.         0.33333333 0.33333333 0.        ]
 [0.         0.         0.66666667 0.         0.         0.33333333]]
[[0.         0.         0.66666667 0.         0.         0.33333333]
 [0.         0.         0.66666667 0.         0.         0.33333333]
 [0.16666667 0.16666667 0.         0.33333333 0.33333333 0.        ]
 [0.         0.         0.66666667 0.         0.         0.33333333]
 [0.         0.         0.66666667 0.         0.         0.33333333]
 [0.16666667 0.16666667 0.         0.33333333 0.33333333 0.        ]]
[[0.16666667 0.16666667 0.         0.33333333 0.33333333 0.        ]
 [0.16666667 0.16666667 0.         0.33333333 0.33333333 0.        ]
 [0.         0.         0.666666

In [3]:
P=np.array(\
  [[0,0,1,0,0,0],\
   [0,0,1,0,0,0],\
   [1/4, 1/4, 0, 1/4,1/4,0],\
   [0, 0, 1/2, 0,0,1/2],\
   [0, 0, 1/2, 0,0,1/2],\
   [0, 0,0, 1/2, 1/2,0]])

#print("P_maze=\n",P)

#Matrix of 5-step transitions
print("P_maze 2-step=\n",matrix_power(P,2))
print("----------------")
print("P_maze 3-step=\n",matrix_power(P,3))
print("----------------")
print("P_maze 4-step=\n",matrix_power(P,4))
print("----------------")
print("P_maze 5-step=\n",matrix_power(P,5))
print("----------------")
#If the rat starts uniformely in any room, 
#find the probability of the rat being in room 6 at time 10.

#pi_0=[1/6,1/6,1/6,1/6,1/6,1/6]
#pi_10=pi_0 @ matrix_power(P,10)
#print("pi_10",pi_10)

#print("P^5\n",matrix_power(P,5))
#print("P^10\n",matrix_power(P,10))
#print("P^50\n",matrix_power(P,50))
print("P^51\n",matrix_power(P,51))
print("P^52\n",matrix_power(P,52))

P_maze 2-step=
 [[0.25  0.25  0.    0.25  0.25  0.   ]
 [0.25  0.25  0.    0.25  0.25  0.   ]
 [0.    0.    0.75  0.    0.    0.25 ]
 [0.125 0.125 0.    0.375 0.375 0.   ]
 [0.125 0.125 0.    0.375 0.375 0.   ]
 [0.    0.    0.5   0.    0.    0.5  ]]
----------------
P_maze 3-step=
 [[0.     0.     0.75   0.     0.     0.25  ]
 [0.     0.     0.75   0.     0.     0.25  ]
 [0.1875 0.1875 0.     0.3125 0.3125 0.    ]
 [0.     0.     0.625  0.     0.     0.375 ]
 [0.     0.     0.625  0.     0.     0.375 ]
 [0.125  0.125  0.     0.375  0.375  0.    ]]
----------------
P_maze 4-step=
 [[0.1875  0.1875  0.      0.3125  0.3125  0.     ]
 [0.1875  0.1875  0.      0.3125  0.3125  0.     ]
 [0.      0.      0.6875  0.      0.      0.3125 ]
 [0.15625 0.15625 0.      0.34375 0.34375 0.     ]
 [0.15625 0.15625 0.      0.34375 0.34375 0.     ]
 [0.      0.      0.625   0.      0.      0.375  ]]
----------------
P_maze 5-step=
 [[0.       0.       0.6875   0.       0.       0.3125  ]
 [0.       0.  

In [11]:
pi0 = [ 1,0,0,0,0,0]
result = pi0 @ matrix_power(P,101)
print(result)

[0.         0.         0.66666667 0.         0.         0.33333333]


In [18]:
P=[[0,0.3,0.4,0.3],\
   [0, 0.2, 0,0.8],\
   [0, 1, 0, 0],\
   [0, 0.5, 0.5,0]]

P=np.array(P)

print("P^2\n",matrix_power(P,2))
Pi0 = [ 1/6, 1/6, 1/6, 1/6 ]
print(Pi0 @ matrix_power(P,1))
print("P^3\n",matrix_power(P,3))
print("P^5\n",matrix_power(P,5))
print("P^10\n",matrix_power(P,10))
print("P^15\n",matrix_power(P,15))
print("P^16\n",matrix_power(P,16))
print("P^50\n",matrix_power(P,50))
print("P^51\n",matrix_power(P,51))

P^2
 [[0.   0.61 0.15 0.24]
 [0.   0.44 0.4  0.16]
 [0.   0.2  0.   0.8 ]
 [0.   0.6  0.   0.4 ]]
[0.         0.33333333 0.15       0.18333333]
P^3
 [[0.    0.392 0.12  0.488]
 [0.    0.568 0.08  0.352]
 [0.    0.44  0.4   0.16 ]
 [0.    0.32  0.2   0.48 ]]
P^5
 [[0.      0.48928 0.1568  0.35392]
 [0.      0.47712 0.2272  0.29568]
 [0.      0.3696  0.176   0.4544 ]
 [0.      0.4688  0.128   0.4032 ]]
P^10
 [[0.         0.45731625 0.18406298 0.35862077]
 [0.         0.4502314  0.1862359  0.3635327 ]
 [0.         0.45441587 0.17311232 0.37247181]
 [0.         0.46000282 0.18064896 0.35934822]]
P^15
 [[0.         0.45434582 0.18220079 0.36345338]
 [0.         0.45407132 0.18160228 0.3643264 ]
 [0.         0.455408   0.18138745 0.36320456]
 [0.         0.45470685 0.18230343 0.36298972]]
P^16
 [[0.         0.45479665 0.18172669 0.36347666]
 [0.         0.45457974 0.1821632  0.36325706]
 [0.         0.45407132 0.18160228 0.3643264 ]
 [0.         0.45473966 0.18149486 0.36376548]]
P^50
 [[0. 

In [2]:
P=[[.5,.5,0,0],\
   [.9999,0, .0001,0],\
   [0, 0.01, 0, 0.99],\
   [0, 0, 0.01,0.99]]

print("P^3\n",matrix_power(P,3))
print("P^5\n",matrix_power(P,5))
print("P^10\n",matrix_power(P,10))
print("P^15\n",matrix_power(P,15))
print("P^16\n",matrix_power(P,16))
print("P^50\n",matrix_power(P,50))
print("P^51\n",matrix_power(P,51))
print("P^500\n",matrix_power(P,500))
print("P^5000\n",matrix_power(P,5000))
print("P^50000\n",matrix_power(P,50000))
print("P^500000\n",matrix_power(P,500000))

P^3
 [[6.24950000e-01 3.74975500e-01 2.50000000e-05 4.95000000e-05]
 [7.49876005e-01 2.49975000e-01 5.09851000e-05 9.80100000e-05]
 [4.99950000e-03 5.09851000e-03 9.80100000e-03 9.80100990e-01]
 [9.99900000e-05 9.90000000e-05 9.90001000e-03 9.89901000e-01]]
P^5
 [[6.56150504e-01 3.43706881e-01 3.19850750e-05 1.10630075e-04]
 [6.87345021e-01 3.12444262e-01 3.89689027e-05 1.71747922e-04]
 [6.39637530e-03 3.89689027e-03 9.80028948e-03 9.79906445e-01]
 [2.23472750e-04 1.73482749e-04 9.89804490e-03 9.89705000e-01]]
P^10
 [[6.66778926e-01 3.32912830e-01 3.57893875e-05 2.72454441e-04]
 [6.65759077e-01 3.33866812e-01 3.62422673e-05 3.37868339e-04]
 [7.15716172e-03 3.62422673e-03 9.79556011e-03 9.79423051e-01]
 [5.50357970e-04 3.41281151e-04 9.89316214e-03 9.89215199e-01]]
P^15
 [[6.66333594e-01 3.33193395e-01 3.73477343e-05 4.35662662e-04]
 [6.66320152e-01 3.33140946e-01 3.80041980e-05 5.00897923e-04]
 [7.46879990e-03 3.80041980e-03 9.79074282e-03 9.78940037e-01]
 [8.80038578e-04 5.05957498e-0

In [2]:
P=[[0,1,0 ],\
   [0,0,1],\
   [1,0,0] ]

In [5]:
print("P^2\n",matrix_power(P,2))
print("P^3\n",matrix_power(P,3))
print("P^4\n",matrix_power(P,4))
print("P^5\n",matrix_power(P,5))
print("P^6\n",matrix_power(P,6))
print("P^7\n",matrix_power(P,7))

P^2
 [[0 0 1]
 [1 0 0]
 [0 1 0]]
P^3
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
P^4
 [[0 1 0]
 [0 0 1]
 [1 0 0]]
P^5
 [[0 0 1]
 [1 0 0]
 [0 1 0]]
P^6
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
P^7
 [[0 1 0]
 [0 0 1]
 [1 0 0]]
